# Generated by Django 5.2.9 on 2025-12-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_index_id_ProductSequenceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Article.index_id序列锁',
                'verbose_name_plural': 'Article.index_id序列锁',
            },
        ),
    ]
