# Generated by Django 5.2.9 on 2025-12-15 18:56

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(max_length=10, unique=True, validators=[user.models.validate_student_number], verbose_name='学号'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('nickname__gt', '')), fields=('nickname',), name='unique_non_empty_nickname'),
        ),
    ]
